### ISSUE TITLE
Add support to Mastodon

### ISSUE THREAD

**Issue by ezeoleaf** [ezeoleaf/larry#102]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implement the API to Mastodon to publish repos

**Describe alternatives you've considered**
\ -

**Additional context**
[Docs](https://docs.joinmastodon.org/api/)

**Comment by till** [comment]
Did you start a bot? Otherwise I would run one.

**Comment by ezeoleaf** [comment]
Yes, go ahead, you can run one as did not have time to finish setting up everything
