### ISSUE TITLE
Tweet cannot be published if it is too long

### ISSUE THREAD

**Issue by ezeoleaf** [ezeoleaf/larry#40]
**Describe the bug**
If the generated tweet is too long it cannot be published and we receive an error from Twitter API.

**To Reproduce**
1. Generate a Content with long title and description
2. Try to publish it via Github API
3. See error

**Expected behavior**
The description of the tweet should be truncated to fit in the Tweet size. Ideally only the description should be truncated

**Screenshots**
None

**Additional context**
Maybe add some tests to replicate this issue

**Comment by Shubhcoder** [comment]
Hi, @ezeoleaf 

I have submitted a PR for this issue. Can you please have a look into it?

Actually, I am new to both open source and golang community. So, feedbacks will be really appreciated.

Thank you.
