### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by hollycoder** [ezeoleaf/larry#41]
I tried to install this package and followed the documentation
```
git clone https://github.com/ezeoleaf/larry.git
cd larry
go install 
```
But I get an error message that says:
`no Go files in /Users/home/x/x/larry`

I tried to install another package with go install ([hey package](https://github.com/rakyll/hey)) and it worked with no issues.
Any ideas?

**Comment by ezeoleaf** [comment]
Yes, you're right. After a huge refactor I forgot to modify the install section of the README. Good catch :)

The new steps are:
```
git clone https://github.com/ezeoleaf/larry.git
cd larry/cmd/larry
go install 
```

After that you will see the larry executable in the folder you have specified for binaries files.

Also you can use the make command like:
```
git clone https://github.com/ezeoleaf/larry.git
cd larry
make build
```

And you will see the executable inside the project's bin folder.

Thanks, will fix the documentation
