### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ezeoleaf** [ezeoleaf/larry#44]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Improve documentation to add the providers and publishers supported at the moment and which env variables are needed for them.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by Kannav02** [comment]
Hey, specifically which file are you talking about that needs to have this documentation?

**Comment by ezeoleaf** [comment]
I added some small info in the README, but I think we can create a file specific for publishers and providers where we can add more information if we have more in the future and then link it in the README file
Also, I think it would be a good idea to add more information on how to get the values need for the env variables (from Twitter or from Github)

**Comment by Kannav02** [comment]
Hey , can you assign me the task of creating a specific file for publishers and providers ?

**Comment by ezeoleaf** [comment]
Yes, totally! Thanks for the help :)

**Comment by Kannav02** [comment]
Hey @ezeoleaf do you want me to link the documentation file in the README file?

**Comment by ezeoleaf** [comment]
@Kannav02 I think that would be a good idea. Maybe using a relative link in the README file

**Comment by Kannav02** [comment]
Okk, I'll work upon it then

**Comment by ezeoleaf** [comment]
Thanks! Yes, the rest looks ok. We may need to rename is as the new file is named only Publishers-doc... and it is for both publishers and providers. What do you think?

**Comment by Kannav02** [comment]
Ok , I'll rename it then

**Comment by Kannav02** [comment]
Hey , I wanted to ask you where should I add the link for the documentation in the README file , Any Specific topic under which you would like it to be linked ?

**Comment by ezeoleaf** [comment]
Maybe inside the Usage section, there is one subsection called **Available Providers and Publishers** that you can renamed to Providers and Publishers and add the link inside that one?
What do you think?

**Comment by Kannav02** [comment]
Yeah, that should be good
