### ISSUE TITLE
Allow local file as source of data

### ISSUE THREAD

**Issue by ezeoleaf** [ezeoleaf/larry#55]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Fetch messages from a local file so they can be posted. The file could be in different formats so we may need to specify the format in the params when starting the app.
It could be:
- Json: A list of string texts
- CSV: An allow to pass a column name as param to publish the text in that column.

**Describe alternatives you've considered**
Other formats can be included

**Additional context**
No

**Comment by savagedev** [comment]
I would expect the json formatted file to have fields matching the domain.Content struct and the CSV to have column for each of these struct fields, do you agree? For the CSV you say "pass a column name as param to publish the text in that column" but that implies this column has one string with all domain.Content fields concatenated. This conflicts with the publisher interface which has a function PublishContent that takes a domain.Content.

**Comment by savagedev** [comment]
I'd like to look at this one next if that's ok with you. This one seems like the foundation that can be used later for both #33 (Google sheet = CSV) and #34 (AWS = an object containing either CSV or Json). 

I think you'd like to have a random repository selected here too? If so, the reservoir sampling technique seems like the best solution for randomly selecting a row from the file.

**Comment by ezeoleaf** [comment]
Yes, I think this is a good approach. The idea is to select anything from the local file, the provider should return an object of type  Content, so with that object then the publisher/s are able to post anything.

**Comment by savagedev** [comment]
Pull request #70 has been submitted for this feature
