### ISSUE TITLE
Redis cache expiration value

### ISSUE THREAD

**Issue by ezeoleaf** [ezeoleaf/larry#58]
### Discussed in https://github.com/ezeoleaf/larry/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **savagedev** June 12, 2022</sup>
Why is the Redis cache expiration periodicity value the same frequency as retrieving a random repo from Github? For example, running "make run-dev", the periodicity is one minute and this same value is used to expire the cached value. This means a randomly selected repo can be selected again too soon. Possibly this is by design? Is so then why? Otherwise it seems the cache expiration value should be a new config setting, independent of the run frequency.</div>

Re add the calculation for the Redis cache expiration value as cacheSize * periodicity instead of periodicity (as it is right now)

**Comment by savagedev** [comment]
Submitted PR #59 to fix this issue.
