### ISSUE TITLE
Add blacklist of repos in cache

### ISSUE THREAD

**Issue by ezeoleaf** [ezeoleaf/larry#7]
**Is your feature request related to a problem? Please describe.**
Yes, sometimes, some tweets are not related to the language itself.

**Describe the solution you'd like**
The idea is to have a list of blacklisted repositories that must be avoided.

**Describe alternatives you've considered**
Having the blacklist in a config file, but not a good idea.

**Comment by Lachie-Young** [comment]
Any example of what query string search returned a repo that should be blacklisted?

**Comment by ezeoleaf** [comment]
Hey @Lachie-Young, my idea actually was to have in Redis some list of blacklisted repos that we (at least at the beginning) can add manually.

So for example, in redis we could have a list with a **blacklist** key and as values we can have [ {repoID1}, {repoID2}, {repoID100} ]. (If this is not possible, then we could add elements to redis that follow the format **blacklist-{repoID}**)

Then, from our provider/s that are consuming Redis, we should have a method called isBlacklisted with a repository ID as argument, that will check in Redis if the repository id is in the blacklisted table and we should not publish it.

At the moment, we are ignoring repositories that are abandoned or archived so this is working ok, but we sometimes find repositories that should not be posted, that's why we want to do this new functionality.

Does this make sense?

**Comment by savagedev** [comment]
@ezeoleaf You mention using the GitHub repo Id but wouldn't it be easier to maintain a list of blacklisted repo URLs like "github.com/boz/kail" or even the full URL "https://github.com/boz/kail" instead? I'm not sure why but I don't even see the repo Id when looking at a repo from the GitHub website.

**Comment by ezeoleaf** [comment]
@savagedev I think the id would be more helpful here as it's an unique id and the url can change if you change the name of the repo or your username (I know is not so common).

We always have the id of the repo using the Github API, but you can also find it in the website by inspecting the website page. You will find an attribute called **octolytics-dimension-repository_id**

<img width="505" alt="image" src="https://user-images.githubusercontent.com/10358977/173774569-dc2d9680-e6ec-4452-8303-26242984c1f3.png">

Or you can use the public URL of the Github API to search for it:
https://api.github.com/repos/ezeoleaf/larry

**Comment by savagedev** [comment]
@ezeoleaf I have this almost complete and in addition to the providers having an isBlacklisted function to check Redis for a blacklist-{repoID} key, I have added a command line argument for the optional blacklist file that will be loaded when Larry runs. This is working nice. 

Originally I had the blacklist loader always clearing out the blacklisted keys from Redis before loading the file but I get the sense you have multiple Larry processes running for different topics and using just one Redis database. This means one process would clear out the other's blacklisted keys.

One way around this would be to include the topic in the blacklist key, e.g., blacklist-{topic}-{repoID} like the isRepoNotInCache function does. This way the blacklist loader can always clear the blacklist keys for just that topic. Let me know how this sounds.

**Comment by ezeoleaf** [comment]
@savagedev Yes, i was facing the same concern, and I think your idea of adding the topic is a good idea.

So we can have:

If topic is defined in the args:
- blacklist-{topic}-{repoID}

If lang is defined:
- blacklist-{lang}-{repoID}

If both topic and lang are defined: (Although this is not used for now)
Then we can check if blacklist-{topic}-{repoID} or blacklist-{lang}-{repoID} exists.
Or having:
- blacklist-{topic}-{lang}-{repoID}

**Comment by savagedev** [comment]
@ezeoleaf The approach I took in the PR is to use topic, lang, or both in the blacklist key. So if both topic and lang are used, the key would look like:

- blacklist-{topic}-{lang}-{repoID}
